---
stages:
  - checks
  - test
  - push

variables:
  GITHUB_USER: lotusnoir


##################################################
# SYNTAX CHECKS
##################################################
yamllint:
  stage: checks
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

ansible-lint:
  stage: checks
  image: lotusnoir/ansible_play
  script:
    - ansible-lint .


######################################################
# RUN MOLECULE FOR FULL TEST SCENARIO
######################################################
molecule:
  stage: test
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
  needs:
    - yamllint
    - ansible-lint
  before_script:
    - molecule --version
  script:
    - molecule test


##################################################
# PUSH CODE WHEN ALL TEST OK
##################################################
push_src_on_github:
  stage: push
  image: alpine:latest
  needs:
    - molecule
  before_script:
    - apk add git openssh-client
    - eval $(ssh-agent -s)
    - echo "${GITHUB_USER_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tUser ansible\n\tStrictHostKeyChecking no\n\tForwardAgent yes\n\n" > ~/.ssh/config
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git config --global user.name "${GITHUB_USER}"
    - git config --global init.defaultBranch main
    - COMMENT=$(git log -1 --pretty=%B | head -1)
  script:
    - git clone git@github.com:${GITHUB_USER}/ansible-apps_wazuh_agent.git /tmp/ansible-apps_wazuh_agent
    - rm -rf .git
    - cp -r . /tmp/ansible-apps_wazuh_agent/
    - cd /tmp/ansible-apps_wazuh_agent
    - git add -A
    - git commit -m "${COMMENT}" || echo "No changes, nothing to commit!"
    - git push
